Repository operate-first/peribolos-as-a-service, pull requests merged in 2022-04, with the labels that each got.

#20 feat: Add task for running peribolos on push event
  pipelines/base/peribolos-run.yaml
Labels: size/M, lgtm, approved

#19 Generate Token for each install and store them as k8 secrets
  manifests/deployment-config.yaml
  manifests/kustomization.yaml
  manifests/route.yaml
  manifests/service-account.yaml
  manifests/service.yaml
  package-lock.json
  package.json
  src/index.ts
Labels: size/XXL, lgtm, approved

#27 setup automation for image build on release
  .aicoe-ci.yaml
  README.md
Labels: lgtm, size/S, approved

#25 feat: Create service account and roles
  manifests/kustomization.yaml
  manifests/role-binding.yaml
  manifests/role.yaml
Labels: size/M, lgtm, approved

#17 feat(dump-config): Create task
  pipelines/base/config-dump.yaml
Labels: size/L, lgtm, approved

#44 rename config file to peribolos.yaml
  pipelines/base/config-dump.yaml
  pipelines/base/peribolos-run.yaml
Labels: lgtm, size/XS, approved

#21 Update app installation token on secret
  package-lock.json
  src/index.ts
Labels: lgtm, size/XL, approved

#40 feat: Add push event controller
  src/index.ts
Labels: size/M, lgtm, approved

#43 add imagestream for controller image
  .aicoe-ci.yaml
  README.md
  manifests/deployment-config.yaml
  manifests/imagestream.yaml
  manifests/kustomization.yaml
Labels: lgtm, size/S, approved, sig/services

#45 feat: split manifests into overlays
  manifests/base/config-dump.yaml
  manifests/base/deployment-config.yaml
  manifests/base/imagestream.yaml
  manifests/base/kustomization.yaml
  manifests/base/peribolos-run.yaml
  manifests/base/role-binding.yaml
  manifests/base/role.yaml
  manifests/base/route.yaml
  manifests/base/secret.yaml
  manifests/base/service-account.yaml
  manifests/base/service.yaml
  manifests/overlays/dev/kustomization.yaml
  manifests/overlays/test/kustomization.yaml
Labels: size/M, lgtm, approved

#28 User unsubscribe
  src/index.ts
Labels: size/XS, approved

#48 fix: Fix namespace variable name in push event
  src/index.ts
Labels: lgtm, size/XS, approved

#42 included dev setup docs
  README.md
Labels: size/M, lgtm, approved

#41 feat: handle org config dump if not present
  .pre-commit-config.yaml
  manifests/base/peribolos-dump-config.yaml
  peribolos-fix/Dockerfile
  peribolos-fix/peribolos.patch
  src/index.ts
Labels: size/L, lgtm, approved

#49 feat: Change building image from Docker to s2i
  .aicoe-ci.yaml
  .dockerignore
  Dockerfile
  README.md
  scripts/build-image.sh
Labels: size/M, lgtm, approved

#50 Add linters and refactor code for maintainability and code reuse
  .nvmrc
  .pre-commit-config.yaml
  .prow.yaml
  README.md
  package-lock.json
  package.json
  src/app.ts
  src/index.ts
  src/probotOnKube.ts
Labels: size/XXL, approved

#75 chore: Use prettier pre-commit hook as well
  .pre-commit-config.yaml
  jest.config.js
  src/app.ts
  test/index.test.ts
Labels: size/M, lgtm, approved

#76 Fix the image patch in CI
  .aicoe-ci.yaml
  manifests/base/deployment-config.yaml
  manifests/base/imagestream.yaml
  manifests/base/kustomization.yaml
  manifests/overlays/dev/imagestream.yaml
  manifests/overlays/dev/kustomization.yaml
  manifests/overlays/prod/imagestream.yaml
  manifests/overlays/prod/kustomization.yaml
  manifests/overlays/test/kustomization.yaml
Labels: size/M, lgtm, approved
