Repository operate-first/peribolos-as-a-service, pull requests merged in 2022-07, with the labels that each got.

#168 fix: wrapOperationWithMetrics status label
  src/app.ts
Labels: lgtm, size/S, approved

#175 fix: Limit push events to .github repo only
  src/app.ts
Labels: lgtm, size/XS, approved

#177 feat: Add basic prometheus alerts
  manifests/base/kustomization.yaml
  manifests/base/monitoring/kustomization.yaml
  manifests/base/monitoring/prometheusrule.yaml
Labels: size/M, lgtm, approved

#163 feat: Update tasks for peribolos upstream change
  .github/actions/build-peribolos/action.yaml
  .github/workflows/pr.yaml
  .github/workflows/push.yaml
  .github/workflows/release.yaml
  manifests/base/kustomization.yaml
  manifests/base/tasks/dump-config.yaml
  manifests/base/tasks/run.yaml
  manifests/overlays/prod/kustomization.yaml
  manifests/overlays/stage/kustomization.yaml
  peribolos-fix/Dockerfile
  peribolos-fix/peribolos.patch
Labels: size/L, lgtm, approved

#179 docs: Fix README typos
  README.md
Labels: lgtm, size/XS, approved

#183 feat: Add OCP link to check
  package-lock.json
  package.json
  src/app.ts
  src/cache.ts
Labels: size/L, lgtm, approved

#185 fix: Fix how metric labels are calculated
  src/app.ts
Labels: size/L, lgtm, approved
