Repository operate-first/peribolos-as-a-service, pull requests merged in 2022-06, with the labels that each got.

#138 refactor: Extract Kubernetes and Prometheus libraries into separate extensions
  manifests/overlays/dev/kustomization.yaml
  package-lock.json
  package.json
  src/app.ts
  src/index.ts
  src/metrics.ts
  src/probotOnKube.ts
Labels: size/XXL, lgtm, approved

#147 chore: Add acknowledgments, contributors, deployment links to readme
  ACKNOWLEDGMENTS.md
  CONTRIBUTORS.md
  README.md
Labels: size/M, lgtm, approved

#153 feat: Relocate Probot repositories to Operate First
  .github/workflows/push.yaml
  .github/workflows/release.yaml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  SECURITY.md
  SUPPORT.md
  manifests/base/kustomization.yaml
  manifests/overlays/prod/kustomization.yaml
  manifests/overlays/stage/kustomization.yaml
  package-lock.json
  package.json
  src/app.ts
Labels: size/L, approved

#146 feat(controller): Create GitHub check for taskRuns
  manifests/base/tasks/run.yaml
  src/app.ts
Labels: size/L, lgtm, approved
