Repository operate-first/peribolos-as-a-service, pull requests merged in 2022-05, with the labels that each got.

#78 chore(ci): Use Github Actions and Semantic Release
  .aicoe-ci.yaml
  .github/ISSUE_TEMPLATE/promote.md
  .github/ISSUE_TEMPLATE/release.md
  .github/actions/build-controller/action.yaml
  .github/actions/build-peribolos/action.yaml
  .github/actions/check-maintainer-role/action.yaml
  .github/actions/test/action.yaml
  .github/workflows/pr.yaml
  .github/workflows/promote.yaml
  .github/workflows/push.yaml
  .github/workflows/release.yaml
  .s2ibase
  package-lock.json
  package.json
  scripts/build-image.sh
Labels: size/XXL, approved

#79 test: Init tests
  .gitleaks.toml
  .pre-commit-config.yaml
  test/app.test.ts
  test/fixtures/issues.opened.json
  test/fixtures/mock-cert.pem
Labels: size/M, approved

#81 chore: Enable renovate (for js/ts) and dependabot (for github actions)
  .github/dependabot.yml
  .github/renovate.json
Labels: lgtm, size/S, approved

#87 chore(renovate): Make renovate sign off commits
  .github/renovate.json
Labels: lgtm, size/XS, approved

#93 chore(dependabot): Remove
  .github/dependabot.yml
Labels: size/S

#80 docs: Update docs for publishing
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/security.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE
  README.md
  SECURITY.md
  SUPPORT.md
  app.yml
  static/robot.png
  static/robot.svg
Labels: lgtm, size/XL, approved

#100 fix: Deployment CPU request is wrong format
  manifests/base/controller/deployment.yaml
Labels: size/XS, approved

#101 fix: Deployment CPU request is wrong format [2]
  manifests/base/controller/deployment.yaml
Labels: size/XS, approved

#102 fix: Cleanup some labels in deployment manifests
  manifests/base/controller/deployment.yaml
Labels: size/XS, approved

#103 fix: Use https route
  manifests/base/controller/route.yaml
Labels: lgtm, size/XS, approved

#99 chore(ci): Expire commit tagged images in a week
  .github/actions/set-expiration/action.yaml
  .github/workflows/push.yaml
  .github/workflows/release.yaml
Labels: size/M, lgtm, approved

#120 chore(ci): Fix promote workflow
  .github/workflows/promote.yaml
Labels: size/XS, approved

#125 fix: Probot on kube doesn't work in prod builds
  manifests/base/tasks/dump-config.yaml
  src/app.ts
  src/probotOnKube.ts
  tsconfig.json
Labels: size/L, approved

#126 fix(controller): Role to allow secret deletion
  manifests/base/controller/role.yaml
Labels: size/XS, approved

#127 fix(peribolos): Swap base image so we get SSL
  manifests/base/tasks/dump-config.yaml
  manifests/base/tasks/run.yaml
  peribolos-fix/Dockerfile
Labels: size/M, approved

#128 :bar_chart: introduce metrics for the peribolos app
  Metrics.md
  manifests/base/controller/kustomization.yaml
  manifests/base/controller/servicemonitor.yaml
  package-lock.json
  package.json
  src/app.ts
  src/index.ts
  src/metrics.ts
Labels: lgtm, size/XL, approved
